export const posts = [
    {
        id: 1,
        avatar: '/images/seller-icon.png',
        username: '난난판다',
        role: '아날로그 독서가',
        title: '표지 예쁘고, 재밌는 책 추천 좀',
        fullContent: '표지는 마음에 드는데 막상 내용은 별로일 때가 많아서 추천이 간절해요ㅠㅠ 취향 맞는 책 찾고 싶어요. 다들 어떤 책 읽으시나요? 댓글로 추천 부탁드립니다!',
        likes: 1,
        comments: [
            { id: 1, username: '독서광', text: '저는 최근에 "달러구트 꿈 백화점" 읽었는데 정말 좋았어요!' },
            { id: 2, username: '책벌레', text: '표지 예쁜 책은 "모순"도 괜찮아요. 내용도 좋아요.' },
            { id: 3, username: '디자이너', text: '표지가 예쁘면 소장욕구가 생기는 것 같아요.' },
            { id: 4, username: '수집가', text: '저는 표지 때문에 책을 사기도 해요.' }
        ],
        image: '/images/모순.png',
        time: '5분 전',
        type: 'all',
        isLiked: false,
        category: '자유글',
        thumbnail: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?q=80&w=1887&auto=format&fit=crop'
    },
    {
        id: 2,
        avatar: '/images/seller-icon.png',
        username: '판다다',
        role: '전자책 매니아',
        title: '최근 종이책이 유행이네요',
        fullContent: '그런데 최근 책값이 많이 올라서 부담이 되네요 새 책은 너무 비싸서 중고로 사고 싶어서 가입했어요. 다들 중고책은 어디서 구매하시나요? 좋은 팁 있으면 공유해주세요!',
        likes: 3,
        comments: [
            { id: 1, username: '중고책사랑', text: '당근마켓이나 알라딘 중고서점 자주 이용해요!' },
            { id: 2, username: '책방지기', text: '저희 동네 작은 책방에서도 중고책 팔아요~' },
            { id: 3, username: '온라인서점', text: '온라인 중고서점도 잘 찾아보면 싸게 살 수 있어요.' },
            { id: 4, username: '도서관파', text: '저는 주로 도서관에서 빌려봐요.' },
            { id: 5, username: '북클럽', text: '북클럽 가입하면 할인쿠폰 많이 줘서 좋아요.' },
            { id: 6, username: '이벤트참여', text: '출판사 이벤트 참여하면 책을 공짜로 얻을 수도 있어요.' },
            { id: 7, username: '책교환', text: '친구랑 책 바꿔보는 것도 좋은 방법이에요.' },
            { id: 8, username: '독서모임', text: '독서모임에서 책 정보를 많이 얻어요.' },
            { id: 9, username: '지역서점', text: '지역 서점에서도 할인 행사를 많이 해요.' },
            { id: 10, username: '전자책구독', text: '전자책 구독 서비스도 고려해보세요.' },
            { id: 11, username: '리뷰이벤트', text: '리뷰 이벤트 참여하면 포인트를 줘서 책 살 때 쓸 수 있어요.' },
            { id: 12, username: '중고나라', text: '중고나라도 잘 찾아보면 득템할 수 있어요.' },
            { id: 13, username: '대학서점', text: '대학 서점에서도 가끔 할인 행사를 해요.' },
            { id: 14, username: '해외직구', text: '원서는 해외 직구로 사면 더 싸게 살 수 있어요.' }
        ],
        image: '/images/불편한 편의점.png',
        time: '13분 전',
        type: 'popular',
        isLiked: false,
        category: '책 추천',
        thumbnail: null
    },
    {
        id: 3,
        avatar: '/images/seller-icon.png',
        username: '판따',
        role: '동화 육아 마스터',
        title: '잠자기 전에 동화책 매일 읽어줘요',
        fullContent: '아이에게 좋다길래, 중고로 전권 구매했어요~ 좋은 거래자분 만나서 합리적인 가격에 얻었어요! 혹시 아이에게 읽어주기 좋은 동화책 있으면 추천해주세요!',
        likes: 7,
        comments: [
            { id: 1, username: '육아맘', text: '저희 아이는 "구름빵" 정말 좋아해요!' },
            { id: 2, username: '동화작가', text: '전래동화나 이솝우화도 좋아요.' },
            { id: 3, username: '아빠는육아중', text: '저는 "강아지똥" 읽어주면서 많이 울었어요.' },
            { id: 4, username: '그림책수집가', text: '앤서니 브라운 작가 책들이 다 좋아요.' },
            { id: 5, username: '워킹맘', text: '저는 자기 전에 "사랑해 사랑해 사랑해" 읽어줘요.' },
            { id: 6, username: '책읽는아이', text: '아이가 직접 고르게 하는 것도 좋은 방법이에요.' },
            { id: 7, username: '다둥이맘', text: '아이들마다 취향이 달라서 여러 종류를 읽어주는게 좋아요.' },
            { id: 8, username: '소아과의사', text: '잠들기 전 책 읽어주는 습관은 아이의 정서 발달에 정말 좋아요.' },
            { id: 9, username: '유치원선생님', text: '아이들이 좋아하는 책은 계속 반복해서 읽어줘도 좋아해요.' }
        ],
        image: '/images/역행자.jpeg',
        time: '21분 전',
        type: 'my-posts',
        isLiked: false,
        category: '분실',
        thumbnail: null
    },
    {
        id: 4,
        avatar: '/images/seller-icon.png',
        username: '난난판다',
        role: '아날로그 독서가',
        title: '읽고 싶은 책이 너무 많아요',
        fullContent: '요즘 읽고 싶은 책이 너무 많은데 시간이 없네요. 다들 어떻게 시간 관리하시나요? 독서 시간을 늘리는 팁이 있다면 공유해주세요!',
        likes: 5,
        comments: [
            { id: 1, username: '시간관리왕', text: '저는 출퇴근 시간에 오디오북 들어요!' },
            { id: 2, username: '독서습관', text: '매일 30분씩이라도 꾸준히 읽는 게 중요해요.' }
        ],
        image: '/images/세이노의 가르침.jpeg',
        time: '1시간 전',
        type: 'all',
        isLiked: false,
        category: '자유글',
        thumbnail: null
    },
    {
        id: 5,
        avatar: '/images/seller-icon.png',
        username: '판다다',
        role: '전자책 매니아',
        title: '전자책 리더기 추천해주세요',
        fullContent: '전자책 리더기 구매하려고 하는데 어떤 제품이 좋을까요? 사용 후기 부탁드립니다! 특히 눈의 피로도가 적은 제품이면 좋겠어요.',
        likes: 10,
        comments: [
            { id: 1, username: '리더기유저', text: '크레마 사운드업 추천해요! 가볍고 좋아요.' },
            { id: 2, username: '페이퍼프로', text: '저는 리디 페이퍼 프로 쓰는데 만족합니다.' },
            { id: 3, username: '오닉스포크', text: '오닉스 포크도 괜찮아요. 안드로이드 기반이라 활용도가 높아요.' },
            { id: 4, username: '킨들', text: '원서 많이 읽으시면 킨들도 좋은 선택이에요.' },
            { id: 5, username: '가성비갑', text: '가성비는 크레마가 제일 좋은 것 같아요.' },
            { id: 6, username: '디자인중시', text: '디자인은 리디 페이퍼가 제일 예뻐요.' },
            { id: 7, username: '화면크기', text: '화면 큰 거 원하시면 오닉스 노트 에어나 킨들 스크라이브도 알아보세요.' },
            { id: 8, username: '중고거래', text: '리더기는 중고로 사도 괜찮아요. 상태 좋은 매물 많아요.' }
        ],
        image: '/images/도둑맞은 집중력.jpeg',
        time: '2시간 전',
        type: 'popular',
        isLiked: false,
        category: '책 추천',
        thumbnail: null
    },
    {
        id: 6,
        avatar: '/images/seller-icon.png',
        username: '서연맘',
        role: '아날로그 독서가',
        title: '다 읽은 책들, 어떻게 하시나요?',
        fullContent: '책장에 자리가 없어서 고민이에요. 다들 다 읽은 책은 어떻게 처리하시나요? 중고로 파시나요, 아니면 기부하시나요? 좋은 방법 있으면 공유해주세요!',
        likes: 12,
        comments: [
            { id: 1, username: '책정리달인', text: '저는 알라딘 중고서점에 팔아요. 상태 좋으면 가격도 잘 쳐줘요.' },
            { id: 2, username: '나눔천사', text: '아름다운 가게에 기부하는 것도 좋은 방법이에요.' },
            { id: 3, username: '미니멀리스트', text: '저는 그냥 버려요. 미련을 갖지 않는게 중요해요.' },
            { id: 4, username: '책테크', text: '희귀한 책은 중고서점에서 비싸게 팔릴수도 있어요.' },
            { id: 5, username: '환경보호', text: '종이로 된 책은 재활용이 가능해요.' }
        ],
        image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?q=80&w=1887&auto=format&fit=crop',
        time: '1시간 전',
        type: 'all',
        isLiked: false,
        category: '자유글',
        thumbnail: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?q=80&w=1887&auto=format&fit=crop'
    },
    {
        id: 7,
        avatar: '/images/seller-icon.png',
        username: '추리소설광',
        role: '장르소설 매니아',
        title: '히가시노 게이고 신작 읽어보신 분?',
        fullContent: '이번에 나온 신작 "블랙 쇼맨과 이름 없는 마을의 살인" 읽어보신 분 계신가요? 재밌는지 궁금해요. 스포일러는 말고요!',
        likes: 25,
        comments: [
            { id: 1, username: '게이고팬', text: '저는 정말 재밌게 읽었어요! 역시 히가시노 게이고다 싶었어요.' },
            { id: 2, username: '추리왕', text: '초반엔 좀 지루했는데 뒤로 갈수록 흥미진진해요.' },
            { id: 3, username: '기대중', text: '저도 읽어보려고 장바구니에 담아놨어요.' },
            { id: 4, username: '전작팬', text: '전작에 비하면 조금 아쉬웠어요.' },
            { id: 5, username: '영화화기대', text: '이것도 영화로 나오면 재밌을 것 같아요.' },
            { id: 6, username: '도서관예약', text: '도서관에 예약해놨는데 빨리 읽고 싶네요.' },
            { id: 7, username: '주말독서', text: '주말에 정주행하려고 벼르고 있습니다.' },
            { id: 8, username: '강추', text: '저는 개인적으로 강추합니다!' }
        ],
        image: null,
        time: '3시간 전',
        type: 'popular',
        isLiked: false,
        category: '책 추천',
        thumbnail: null
    },
    {
        id: 8,
        avatar: '/images/seller-icon.png',
        username: '책주인찾아요',
        role: '선한이웃',
        title: '2호선에서 \'모순\' 책 잃어버리신 분',
        fullContent: '오늘 아침 8시쯤 2호선에서 양귀자 작가님의 \'모순\' 책을 주웠습니다. 책 상태도 좋고, 예쁜 책갈피도 꽂혀 있어서 주인 찾아드리고 싶어요. 연락주세요!',
        likes: 5,
        comments: [
            { id: 1, username: '감동', text: '세상 아직 살만하네요. 좋은 일 하셨어요!' },
            { id: 2, username: '지하철유실물', text: '2호선 유실물 센터에도 한번 연락해보세요!' }
        ],
        image: null,
        time: '5시간 전',
        type: 'my-posts',
        isLiked: false,
        category: '분실',
        thumbnail: null
    }
];
